<?php

use phalconer\i18n\translation\source\adapter\EchoAdapter;

$t = isset($t) ? $t : isset($this->translator) ? $this->translator->getAdapter() : new EchoAdapter();
$this->tag->setTitle($t->_('Sign in'));
?>

<?php $this->partial('alert'); ?>

<div class="row">
    <div class="col-md-4 col-md-offset-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?= $this->tag->getTitle() ?></h3>
            </div>
            <div class="panel-body">
                <form id="login-form" action="/user/login" method="post">
                    <input name="<?= $this->security->getTokenKey() ?>" value="<?= $this->security->getToken() ?>" type="hidden">
                    <div class="form-group field-login-form-login required">
                        <label class="control-label" for="login-form-login"><?= $t->_('Username or email') ?></label>
                        <input id="login-form-login" class="form-control" name="login-form[login]" autofocus="autofocus" tabindex="1" aria-required="true" type="text">

                        <div class="help-block"></div>
                    </div>
                    <div class="form-group field-login-form-password required">
                        <label class="full-width" for="login-form-password"><?= $t->_('Password') ?><a class="pull-right" href="/user/forgot" tabindex="5"><?= $t->_('Forgot password?') ?></a></label>
                        <input id="login-form-password" class="form-control" name="login-form[password]" tabindex="2" aria-required="true" type="password">

                        <div class="help-block"></div>
                    </div>
                    <div class="form-group field-login-form-rememberme">
                        <input name="login-form[rememberMe]" value="0" type="hidden">
                        <label><input id="login-form-rememberme" name="login-form[rememberMe]" value="1" checked="" tabindex="4" type="checkbox"> <?= $t->_('Remember me next time') ?></label>

                        <div class="help-block"></div>
                    </div>
                    <button type="submit" class="btn btn-primary btn-block" tabindex="3"><?= $t->_('Sign in') ?></button>
                </form>
            </div>
        </div>
        
        <p class="text-center">
            <?= $t->_('New to %name%?', ['name' => $t->_('My Company')]) . ' ' . $this->tag->linkTo('/user/register', $t->_('Create an account')) . '.' ?>
        </p>
        
        <?php if ($module->enableConfirmation): ?>
            <p class="text-center">
                <?= $this->tag->linkTo('/user/registration/resend', $t->_('Didn\'t receive confirmation message?')) ?>
            </p>
        <?php endif ?>
        <div id="w0"><ul class="auth-clients"></ul></div>
    </div>
</div>
